/// <reference path="./woodbury.d.ts" />

/**
 * Previs Generation Node
 * 
 * Creates a PrevisualizationPlan from shot elements generated by element-generation.
 * Shot elements come from the elements array (not from beats directly).
 * Handles nested section structures (acts containing scenes, etc.)
 *
 * @input processedSections: object[] - Sections with scene content
 * @input elements: object[] - Script elements (includes shot elements)
 * @input characters: object[] - Character definitions
 * @input locations: object[] - Location definitions
 * @input assetCollection: object - Asset collection
 * @output previsualizationPlan: object - Complete PrevisualizationPlan object
 */
export async function execute(
  inputs: { processedSections: any[]; elements: any[]; characters: any[]; locations: any[]; assetCollection: any },
  context: ScriptContext,
): Promise<{ previsualizationPlan: object }> {
  const { processedSections, elements, characters, locations, assetCollection } = inputs;

  try {
    // Parse input data (handle both string and object inputs)
    const parsedElements = Array.isArray(elements)
      ? elements.map(el => typeof el === 'string' ? JSON.parse(el) : el)
      : [];
    const parsedCharacters = Array.isArray(characters)
      ? characters.map(char => typeof char === 'string' ? JSON.parse(char) : char)
      : [];
    const parsedLocations = Array.isArray(locations)
      ? locations.map(loc => typeof loc === 'string' ? JSON.parse(loc) : loc)
      : [];
    const parsedAssets = typeof assetCollection === 'string' ? JSON.parse(assetCollection) : assetCollection;
    const parsedSections = Array.isArray(processedSections)
      ? processedSections.map(section => typeof section === 'string' ? JSON.parse(section) : section)
      : [];

    // Flatten nested sections to get all scenes
    const allScenes = flattenScenes(parsedSections);
    
    context.log(`Previs generation starting with ${parsedElements.length} elements, ${allScenes.length} scenes`);

    // Extract shot elements from the elements array (generated by element-generation)
    const shotElements = parsedElements.filter((el: any) => el.type === 'shot');
    
    context.log(`Found ${shotElements.length} shot elements in elements array`);

    // If no shot elements exist, generate previs frames for each scene based on beats
    if (shotElements.length === 0) {
      context.log('No shot elements found - generating previs from scene beats');
      return await generatePrevisFromScenes(allScenes, parsedCharacters, parsedLocations, parsedAssets, context);
    }

    // Create previsualization shots from shot elements
    const previsualizationShots: any[] = [];
    let shotOrder = 1;

    for (const shotElement of shotElements) {
      // Find the scene this shot belongs to by matching location or context
      const scene = allScenes.find(s => s.type === 'scene');
      const locationId = scene?.locationId || scene?.sceneHeading?.location || null;

      // Extract character IDs from dialogue elements
      const dialogueElements = parsedElements.filter((el: any) => el.type === 'dialogue');
      const characterIds = [...new Set(dialogueElements.map((el: any) => el.characterId).filter(Boolean))];

      // Find corresponding previs-frame asset
      const assetId = parsedAssets?.assets?.find((asset: any) =>
        asset.type === 'previs-frame' && asset.metadata?.shotElementId === shotElement.id
      )?.id || null;

      // Generate shot description and camera intent using LLM
      const shotText = shotElement.shotText || shotElement.content || 'Shot';
      const camMove = shotElement.cameraMovement || 'None specified';
      const frameSize = shotElement.frameSize || 'Not specified';
      const locName = parsedLocations.find((loc: any) => loc.id === locationId)?.name || locationId || 'Unknown';
      const charNames = characterIds.map(id => parsedCharacters.find((char: any) => char.id === id)?.name || id).join(', ') || 'None';
      
      const shotPrompt = `Create a detailed previsualization description for this shot element:

Shot Text: ${shotText}
Camera Movement: ${camMove}
Frame Size: ${frameSize}
Location: ${locName}
Characters Present: ${charNames}

Provide:
1. A detailed visual description of what the shot shows
2. Camera intent (e.g., "Close-up to show emotion", "Wide shot to establish location")
3. Composition notes (e.g., "Rule of thirds", "Low angle for power")
4. Lighting description (e.g., "Natural daylight", "Dramatic shadows")
5. Estimated duration in seconds

Format as JSON with keys: description, cameraIntent, composition, lighting, durationSeconds`;

      const shotDetails = await context.llm.generateJSON(shotPrompt);

      const previsualizationShot = {
        id: `previs_${shotElement.id}`,
        sceneId: scene?.id || 'scene_001',
        shotElementId: shotElement.id,
        shotText: shotElement.shotText || shotElement.content || 'Shot',
        order: shotOrder++,
        locationId: locationId,
        characterIds: characterIds,
        description: shotDetails.description || `Previsualization for shot: ${shotElement.shotText || shotElement.content}`,
        cameraIntent: shotDetails.cameraIntent || 'Standard coverage',
        composition: shotDetails.composition || 'Balanced framing',
        lighting: shotDetails.lighting || 'Natural lighting',
        durationSeconds: shotDetails.durationSeconds || 3,
        assetId: assetId
      };

      previsualizationShots.push(previsualizationShot);
    }

    // Create the complete PrevisualizationPlan
    const previsualizationPlan = {
      collectionName: parsedAssets?.name || 'Script Previsualization',
      shots: previsualizationShots
    };

    context.log(`Generated previsualization plan with ${previsualizationShots.length} shots`);

    return { previsualizationPlan };

  } catch (error) {
    context.log(`Error in previs generation: ${error}`);

    // Return minimal valid previsualization plan on error
    const fallbackPlan = {
      collectionName: 'Script Previsualization',
      shots: []
    };

    return { previsualizationPlan: fallbackPlan };
  }
}

/**
 * Recursively flatten nested sections to extract all scene sections
 */
function flattenScenes(sections: any[]): any[] {
  const scenes: any[] = [];
  
  for (const section of sections) {
    if (section.type === 'scene') {
      scenes.push(section);
    }
    
    // Recursively process children
    if (Array.isArray(section.children) && section.children.length > 0) {
      const childScenes = flattenScenes(section.children);
      scenes.push(...childScenes);
    }
  }
  
  return scenes;
}

/**
 * Generate previs frames from scene beats when no explicit shot elements exist
 */
async function generatePrevisFromScenes(
  scenes: any[],
  characters: any[],
  locations: any[],
  assets: any,
  context: ScriptContext
): Promise<{ previsualizationPlan: object }> {
  const previsualizationShots: any[] = [];
  let shotOrder = 1;

  for (const section of scenes) {
    // Get beats from the correct location
    const beats = section.beats || [];
    const sceneHeading = section.sceneHeading;
    const locationId = section.locationId || null;

    context.log(`Processing scene "${section.title || 'Untitled'}" with ${beats.length} beats`);

    // Generate a previs frame for each beat
    for (const beat of beats) {
      const beatDescription = typeof beat === 'string' ? beat : (beat.description || JSON.stringify(beat));

      // Generate previs details using LLM
      const sceneTitle = section.title || 'Scene';
      const loc = sceneHeading?.location || 'Unknown';
      const tod = sceneHeading?.timeOfDay || 'DAY';
      const charList = characters.map(c => c.name).join(', ');
      
      const previsPrompt = `Create a previsualization frame for this scene beat:

Scene: ${sceneTitle}
Location: ${loc}
Time of Day: ${tod}
Beat: ${beatDescription}

Available Characters: ${charList}

Generate a JSON object with:
- shotText: Brief description of the camera shot (e.g., "WIDE SHOT - Harbor at dawn")
- description: Detailed visual description of what we see
- cameraIntent: Why this shot works for the story
- composition: Framing and visual composition notes
- lighting: Lighting description
- durationSeconds: Estimated duration (3-10 seconds)
- suggestedFrameSize: WIDE, MEDIUM, CLOSE-UP, EXTREME CLOSE-UP
- suggestedCameraMovement: STATIC, PAN, TILT, DOLLY, CRANE, HANDHELD`;

      try {
        const previsDetails = await context.llm.generateJSON(previsPrompt);

        const previsShot = {
          id: `previs_beat_${shotOrder}`,
          sceneId: section.id || `scene_${shotOrder}`,
          beatId: beat.id || `beat_${shotOrder}`,
          shotText: previsDetails.shotText || `Shot ${shotOrder}`,
          order: shotOrder,
          locationId: locationId,
          characterIds: [],
          description: previsDetails.description || beatDescription,
          cameraIntent: previsDetails.cameraIntent || 'Standard coverage',
          composition: previsDetails.composition || 'Balanced framing',
          lighting: previsDetails.lighting || 'Natural lighting',
          durationSeconds: previsDetails.durationSeconds || 5,
          frameSize: previsDetails.suggestedFrameSize || 'MEDIUM',
          cameraMovement: previsDetails.suggestedCameraMovement || 'STATIC',
          assetId: null
        };

        previsualizationShots.push(previsShot);
        shotOrder++;
      } catch (error) {
        context.log(`Error generating previs for beat: ${error}`);
        // Create a basic previs shot on error
        previsualizationShots.push({
          id: `previs_beat_${shotOrder}`,
          sceneId: section.id || `scene_${shotOrder}`,
          beatId: beat.id || `beat_${shotOrder}`,
          shotText: `Shot ${shotOrder}`,
          order: shotOrder,
          description: beatDescription,
          durationSeconds: 5,
          assetId: null
        });
        shotOrder++;
      }
    }
  }

  const previsualizationPlan = {
    collectionName: assets?.name || 'Script Previsualization',
    shots: previsualizationShots
  };

  context.log(`Generated ${previsualizationShots.length} previs frames from scene beats`);

  return { previsualizationPlan };
}
